{application,trpc,
             [{description,[]},
              {vsn,"1.0"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{trpc_app,[]}},
              {env,[]},
              {modules,[tcp_message_parser,trpc_app,trpc_http_conn,
                        trpc_http_ssl_conn,trpc_sup,trpc_tcp_conn]}]}.
